
title: Earthcomputer's Website
email: burtonjae@hotmail.co.uk
github_uname: Earthcomputer
discord_uname: Earthcomputer#9825
youtube_uname: Earthcomputer
twitch_uname: Earthcomputer
twitter_uname: Earthcomputer_

markdown: kramdown
